# Generated by Django 4.2.6 on 2023-10-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
        migrations.RenameModel(
            old_name='Role',
            new_name='Roles',
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='Tasks',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.AlterModelTable(
            name='projects',
            table='PROJECTS',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='ROLES',
        ),
        migrations.AlterModelTable(
            name='taskhistory',
            table='TASK_HISTORY',
        ),
        migrations.AlterModelTable(
            name='tasks',
            table='TASKS',
        ),
        migrations.AlterModelTable(
            name='users',
            table='USERS',
        ),
    ]
