# Generated by Django 4.2.6 on 2023-10-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item_rename_project_projects_rename_role_roles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='role_id',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='users',
            name='assigned_task_id',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.tasks'),
        ),
    ]
