# Generated by Django 4.2.6 on 2023-10-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_users_assigned_project_id_users_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='assigned_project_id',
            new_name='assigned_project',
        ),
    ]
