# Generated by Django 4.2.6 on 2023-10-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_assigned_project_id_users_assigned_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('TO-DO', 'TO-DO'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20),
        ),
    ]
